name: Build .NET

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: "8.0.x"
    secrets:
      CODE_COV_TOKEN:
        required: true

jobs:
  build-and-test:
    name: Build, test and pack .NET library
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure NOTICE file exists and contains valid copyright
        run: |
          if (!(Test-Path -Path "NOTICE")) {
            Write-Host "ERROR: NOTICE file is missing!"
            exit 1
          }
          $content = Get-Content -Path "NOTICE" -Raw
          if ($content -notmatch "Copyright \d{4} Rebels Software") {
            Write-Host "ERROR: NOTICE file does not contain valid copyright statement!"
            exit 1
          }

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: "5.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build .NET project
        run: dotnet build -c Release --no-restore

      - name: Run tests
        run: dotnet test -c Release --no-restore --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODE_COV_TOKEN }}

      - name: Get version from *.csproj file and apply build number if pre-release
        id: version
        run: |
          $csproj = Get-ChildItem -Path . -Filter *.csproj -Recurse | Select-Object -First 1
          
          if (-not $csproj)
          {
            Write-Host "ERROR: No .csproj file found!";
            exit 1
          }
          
          [xml]$proj = Get-Content $csproj.FullName
          $version = $proj.Project.PropertyGroup.Version          
          if (-not $version)
          { 
            Write-Host "ERROR: No Version property found in .csproj file!"; 
            exit 1
          }
          
          if ($version -match "(rc|alpha|beta)") {
            $buildNumber = $env:GITHUB_RUN_NUMBER
            $version = "$version.$buildNumber"
          }

          echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV
          Write-Host "Final Package version: $version"

      - name: Create git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ env.PACKAGE_VERSION }}
          git push origin v${{ env.PACKAGE_VERSION }}

      - name: Pack .NET code into package
        run: |
            Write-Host "Packing using .csproj file..."
            dotnet pack -c Release --no-build --output artifacts -p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - name: Upload package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: artifacts/*.nupkg
